### ISSUE TITLE
Custom template tags

### ISSUE THREAD

**Issue by rg3915** [rg3915/django-experience-2016#19]

**Comment by rafaelribeiroo** [comment]
Bom dia,

Estou sofrendo um pouco pra mexer com isso, em uma rápida vista você consegue notar o que está faltando, agradeço desde já.
Segue:

**time_tags.py:**
```
from django import template
from datetime import date

register = template.Library()

@register.filter
def informa_data(value):
    today = date.today()
    weekday = today.weekday()
    if weekday == 4:
        return str(today)
    else:
        return 'nao e sexta'
```

**template.html:**
Inseri `{% load time_tags %} `logo abaixo abaixo dos:
```
{% extends 'base/base.html' %}
{% load staticfiles %}
```
E em algum determinado lugar dentro do `<body>`:
```
<p>
     {{ instance.content|informa_data }}
</p>
```

**Comment by rg3915** [comment]
@rafaelribeiroo suba seu projeto no GitHub e me passa o link por favor.

**Comment by rg3915** [comment]
https://docs.djangoproject.com/en/1.9/ref/templates/builtins/#built-in-filter-reference

https://docs.djangoproject.com/en/1.9/howto/custom-template-tags/

https://www.djangosnippets.org/search/?q=templatetag

https://www.djangosnippets.org/search/?q=template+filter

https://www.djangosnippets.org/snippets/2130/

**Comment by rg3915** [comment]
https://github.com/rg3915/django-experience/wiki/Custom-template-tags
