### ISSUE TITLE
I/O: Ler/Escrever JSON

### ISSUE THREAD

**Issue by rg3915** [rg3915/django-experience-2016#8]

**Comment by rg3915** [comment]
@cuducos quer dar um tapa nesta Issue tb?
Tem mais uma referência aqui
https://gist.github.com/billroy/3761495
Além da doc.
A ideia é ler e escrever dados em JSON, para depois entrar pro Django onde a gente usa os comandos já conhecidos no manage.

**Comment by cuducos** [comment]
Feito no _PR_ #12
